title:             Lewis's Blog
email:             lewiswei@foxmail.com
description:       This is my blog
author:            Lewis
baseurl:           ""
url:               "http://justb.github.io"

# Social Profiles
twitter_username:  lewiswei7
github_username:   justb
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
